require('core/widgets/date')
require('core/widgets/cpuinfo')
require('core/widgets/coretemp')
require('core/widgets/battery')
require('core/widgets/network')
require('core/widgets/filesystem')
require('core/widgets/memmory')
require('core/widgets/volume')
