--local alsawidget = require('core/widgets/volume')
require('core/widgets/date')
--local mailhover = require('core/widgets/mailhover')
--local weather = require('core/widgets/weather')
require('core/widgets/coretemp')
require('core/widgets/battery')
require('core/widgets/network')
require('core/widgets/memmory')
--require('core/widgets/mpd')
--require('core/widgets/keyboard')
