local alsawidget = require('widgets/volume')
require('widgets/date')
--local mailhover = require('widgets/mailhover')
--local weather = require('widgets/weather')
require('widgets/filesystem')
local cpu = require('widgets/cpuinfo')
local coretemp = require('widgets/coretemp')
local battery = require('widgets/battery')
local network = require('widgets/network')
local mem = require('widgets/memmory')
require('widgets/mpd')
--require('widgets/keyboard')
require('widgets/mail')
