#!/bin/sh
IFS=$'\n'
locale=$( echo $1 | cut -d "_" -f1 )
awesome_version=$( awesome -v | head -1 | cut -d " " -f1-2 | sed 's/v//' )
lua_version=$( lua -v 2>&1 | cut -d " " -f1-2 )
compton_version=$( compton -h | head -1 | sed 's/[(|)]//g' | cut -d "-" -f1,2 | sed 's/git-v//' )
#kde_version=$( kdeinit4 --version | grep "KDE" | sed 's/://' )
sep="<span color=\"#508ED8\">|</span>"
env_string="$awesome_version $sep $lua_version $sep $compton_version"
padding=$(( ${#env_string} - 2 * ${#sep} + 9 ))
echo $env_string
if [ -n "$locale" ]; then
  if [ "ru" = "$locale" ]; then
    echo "<b>Тема Awesome</b>, por <span color=\"#508ED8\">MultiColor</span>" | sed -e :a -e "s/^.\{1,$padding\}$/ & /;ta"
    echo
    echo "<b><span color=\"#508ED8\">Версия Awesome</span></b>" | sed -e :a -e "s/^.\{1,$padding\}$/ & /;ta"
  fi
else
  echo "<b>Theme Awesome</b>, by <span color=\"#508ED8\">MultiColor</span>"
  echo
  echo "<b><span color=\"#508ED8\">awesome Help</span></b>"
fi

