#!/bin/sh
locale=$( echo $1 | cut -d "_" -f1 )
if [ -n "$locale" ]; then
  if [ "pt" = "$locale" ]; then
    echo "* доступны только в этой теме."
    echo
    echo "<span color=\"#508ED8\">Nota:</span> Другие доступные функции в Awesome."
    echo "      Смотрите Awesome помощь."
  fi
else
  echo "* available only in this theme."
  echo
  echo "<span color=\"#508ED8\">Note:</span> Other functions are available via Awesome."
  echo "      See Awesome configuration."
fi

